name: CI

on:
 pull_request:
  branches: [ main ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: instalar dependências
        run: npm install
      - name: rodar os testes
        run: npm test
      
     

